version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - pg

  pg:
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data: