version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - pg

  # mongodb:
  #   image: mongo:latest
  #   restart: always
  #   container_name: "mongodb"
  #   environment:
  #     - MONGO_DATA_DIR=/db/data
  #     - MONGO_LOG_DIR=/dev/null
  #   volumes:
  #     - ./db/data:/data/db
  #   ports:
  #     - 27017:27017
  #   command: mongod --bind_ip_all --smallfiles --logpath=/dev/null # --quiet

  pg:
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data: