import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { Icons } from '../utils';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Running Smart Contracts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="SignUp">   
      {/* {styles.main} */}

        <div>
          <div>
            <Image
              className="index-contract-logo"
              alt=""
              src={Icons.logo}
              width="100px"
              height="100%"
            />
            {/* <span className="index-contract-logo">labs</span> */}
          </div>
        </div>

        <h1 className={styles.title}>
          Welcome to <a target="_blank" href="https://near.org">Near.org!</a>
        </h1>

        <div className={styles.description}>
          <p>
            <a target="_blank" href="https://www.near-sdk.io/"><code className={styles.code}>Near SDK documentation</code></a>
          </p>

          <p>
            <a target="_blank" href="https://docs.near.org/docs/develop/contracts/overview">
              Show functionality of using smart contracts
            </a>
          </p>
        </div>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://near.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
            <Image
              className=""
              alt="https://near.org"
              src={Icons.logo}
              width={100}
              height="100%"
            />
        </a>
      </footer>
    </div>
  )
}
